// Code generated by Kitex v0.8.0. DO NOT EDIT.

package protocolservice

import (
	ue "_5gAKA_go/kitex_gen/_5gAKA_go/UE"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return protocolServiceServiceInfo
}

var protocolServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ProtocolService"
	handlerType := (*ue.ProtocolService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Authenticate": kitex.NewMethodInfo(authenticateHandler, newProtocolServiceAuthenticateArgs, newProtocolServiceAuthenticateResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "ue",
		"ServiceFilePath": `idl\UE.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func authenticateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {

	err := handler.(ue.ProtocolService).Authenticate(ctx)
	if err != nil {
		return err
	}

	return nil
}
func newProtocolServiceAuthenticateArgs() interface{} {
	return ue.NewProtocolServiceAuthenticateArgs()
}

func newProtocolServiceAuthenticateResult() interface{} {
	return ue.NewProtocolServiceAuthenticateResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Authenticate(ctx context.Context) (err error) {
	var _args ue.ProtocolServiceAuthenticateArgs
	var _result ue.ProtocolServiceAuthenticateResult
	if err = p.c.Call(ctx, "Authenticate", &_args, &_result); err != nil {
		return
	}
	return nil
}
