// Code generated by Kitex v0.8.0. DO NOT EDIT.

package protocolservice

import (
	seaf "_5gAKA_go/kitex_gen/_5gAKA_go/SEAF"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return protocolServiceServiceInfo
}

var protocolServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ProtocolService"
	handlerType := (*seaf.ProtocolService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Authenticate": kitex.NewMethodInfo(authenticateHandler, newProtocolServiceAuthenticateArgs, newProtocolServiceAuthenticateResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "seaf",
		"ServiceFilePath": `idl\SEAF.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func authenticateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*seaf.ProtocolServiceAuthenticateArgs)
	realResult := result.(*seaf.ProtocolServiceAuthenticateResult)
	success, err := handler.(seaf.ProtocolService).Authenticate(ctx, realArg.Data)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newProtocolServiceAuthenticateArgs() interface{} {
	return seaf.NewProtocolServiceAuthenticateArgs()
}

func newProtocolServiceAuthenticateResult() interface{} {
	return seaf.NewProtocolServiceAuthenticateResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Authenticate(ctx context.Context, data string) (r string, err error) {
	var _args seaf.ProtocolServiceAuthenticateArgs
	_args.Data = data
	var _result seaf.ProtocolServiceAuthenticateResult
	if err = p.c.Call(ctx, "Authenticate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
