// Code generated by Kitex v0.8.0. DO NOT EDIT.

package protocolservice

import (
	ausf "_5gAKA_go/kitex_gen/_5gAKA_go/AUSF"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler ausf.ProtocolService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
