// Code generated by Kitex v0.8.0. DO NOT EDIT.

package protocolservice

import (
	ausf "_5gAKA_go/kitex_gen/_5gAKA_go/AUSF"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return protocolServiceServiceInfo
}

var protocolServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ProtocolService"
	handlerType := (*ausf.ProtocolService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Authenticate": kitex.NewMethodInfo(authenticateHandler, newProtocolServiceAuthenticateArgs, newProtocolServiceAuthenticateResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "ausf",
		"ServiceFilePath": `idl\AUSF.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func authenticateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ausf.ProtocolServiceAuthenticateArgs)
	realResult := result.(*ausf.ProtocolServiceAuthenticateResult)
	success, err := handler.(ausf.ProtocolService).Authenticate(ctx, realArg.Data)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newProtocolServiceAuthenticateArgs() interface{} {
	return ausf.NewProtocolServiceAuthenticateArgs()
}

func newProtocolServiceAuthenticateResult() interface{} {
	return ausf.NewProtocolServiceAuthenticateResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Authenticate(ctx context.Context, data string) (r string, err error) {
	var _args ausf.ProtocolServiceAuthenticateArgs
	_args.Data = data
	var _result ausf.ProtocolServiceAuthenticateResult
	if err = p.c.Call(ctx, "Authenticate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
